import streamlit as st
import pandas as pd
import altair as alt
import os

st.set_page_config(page_title="Tech Portfolio & Job Tracker", layout="wide")

with st.sidebar:
    
    st.image("https://ui-avatars.com/api/?name=IT+Pro&size=200", caption="Professional Profile") 
    st.markdown("### Contact Details")
    st.write("📧 byadiso@gmail.com")
    st.write("🔗 [My LinkedIn Profile](https://www.linkedin.com/in/desire-byamungu-5b0785a1/)")
    
    # DYNAMIC RESUME DOWNLOAD
    resume_file = "my_resume.pdf"
    if os.path.exists(resume_file):
        with open(resume_file, "rb") as f:
            st.download_button(
                label="📄 Get My Resume(PDF)",
                data=f.read(),
                file_name="Candidate_Resume.pdf",
                mime="application/pdf"
            )
    else:
        st.error("Missing 'my_resume.pdf' in root folder.")


st.title("IT Specialist | Python & React.js Dev 👋")
st.markdown("""
Welcome to my live dashboard. This page demonstrates my ability to bridge **IT Support** with **Python Automation**. 
The feed below is generated by a custom-built NLP bot that scans the market for roles matching my expertise.
""")

st.subheader("Core Technical Competencies")
skills = pd.DataFrame({
    'Skill': ['IT Support','Python Automation', 'Network Security', 'Data Analysis', 'NLP', 'API Integration'],
    'Proficiency': [95, 90, 80, 85, 75, 88]
})
chart = alt.Chart(skills).mark_bar().encode(
    x=alt.X('Proficiency', title='Level (0-100)'),
    y=alt.Y('Skill', sort='-x'),
    color=alt.Color('Proficiency', scale=alt.Scale(scheme='viridis'))
).properties(height=350)
st.altair_chart(chart, use_container_width=True)

st.divider()
st.header("🎯 Automated Job Match Feed")

if os.path.exists("job_listings.xlsx"):
    try:
        df = pd.read_excel("job_listings.xlsx")
        df['Match_Score'] = pd.to_numeric(df['Match_Score'], errors='coerce').fillna(0)
        df = df.sort_values(by="Match_Score", ascending=False).head(20)

        st.write("Real-time analysis of job postings using Cosine Similarity:")
        
        st.dataframe(
            df[['Match_Score', 'Title', 'Company', 'Link']],
            column_config={
                "Link": st.column_config.LinkColumn("Apply / View"),
                "Match_Score": st.column_config.ProgressColumn(
                    "NLP Match Score",
                    format="%d%%",
                    min_value=0,
                    max_value=100
                )
            },
            hide_index=True,
            use_container_width=True
        )
    except Exception as e:
        st.error(f"Error loading live feed: {e}")
else:
    st.info("💡 The background bot is currently scanning the market. Results will populate here automatically.")

st.divider()
with st.expander("🛠️ See System Architecture"):
    st.write("""
    **How this works:**
    - **Extraction:** Python requests data from Job Board APIs.
    - **Deep Scan:** Playwright visits the specific URL to bypass superficial snippets.
    - **NLP Analysis:** Scikit-Learn calculates how similar the job text is to my Resume PDF.
    - **Alerting:** High-priority matches trigger a Telegram Bot message to my phone.
    """)